### ISSUE TITLE
Put this on the web

### ISSUE THREAD

**Issue by thebearjew** [BrightLkms672/EncrypteMe#3]
You can publish this repo as a github pages repo under the domain brightlkms672.github.io/encryptme, so it can be seen and used.

Go figure out how to do that.

**Comment by thebearjew** [comment]
Also, consider using [Font Awesome](http://fontawesome.io/icons/) for some icons at the bottom which you can use to link to your Github profile and the source code for the site!

**Comment by BrightLkms672** [comment]
I did both. Thanks for the tip.
